---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authenticate":
    post:
      summary: Returns a token
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxfQ.zCGBEiC4n4X5jij4lK4nSEtrbebYxELZ6OfBwdm6CJg
        '401':
          description: missing parameter (password or username) or they're wrong
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    default: 'param is missing or the value is empty: username'
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: Student99
                password:
                  type: string
                  default: Password1
              required:
              - username
              - password
  "/api/v1/deauthenticate":
    delete:
      summary: Returns no content
      tags:
      - Authentication
      security:
      - bearer_auth: []
      responses:
        '204':
          description: user deauthenticated successfully
  "/api/v1/signup":
    post:
      summary: Returns a token
      tags:
      - Signup
      parameters: []
      responses:
        '201':
          description: signup successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxfQ.zCGBEiC4n4X5jij4lK4nSEtrbebYxELZ6OfBwdm6CJg
                required:
                - token
        '422':
          description: missing or wrong parameter (probably validations)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      password:
                        type: array
                        properties:
                        - type: string
                          default: can't be blank
                      username:
                        type: array
                        properties:
                        - type: string
                          default: can't be blank
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                      default: Student99
                    password:
                      type: string
                      default: Password1
                  required:
                  - username
                  - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
