---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authenticate":
    post:
      summary: Returns a token
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: authentication successful
        '401':
          description: missing parameter (password or username) or they're wrong
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: Student99
                password:
                  type: string
                  default: Password1
              required:
              - username
              - password
  "/api/v1/deauthenticate":
    delete:
      summary: Returns no content
      tags:
      - Authentication
      security:
      - bearer_auth: []
      responses:
        '204':
          description: user deauthenticated successfully
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
