---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authenticate":
    post:
      summary: Returns a token
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: authentication successful
        '401':
          description: missing username
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
